server:
  port: 9000

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth
    username: postgres
    password:
  jackson:
    serialization:
      INDENT_OUTPUT: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
